### ISSUE TITLE
Make PaymentMethodCollection and ShippingTypeCollection Countable

### ISSUE THREAD

**Issue by Zollerboy1** [lovata/oc-shopaholic-plugin#104]
I have a problem with the PaymentMethodCollection (and the same with ShippingTypeCollection).  
I get it on my order page like it is shown in the example with `PaymentMethodList.make().sort().active()`.

The normal loop is no problem, but I can't access the twig loop variables `loop.last`, `loop.revindex` or `loop.length`.  
Also there is no other method to know, if it is the last iteration of the loop, because neither the twig `length` filter nor the PHP `count()` function work on a PaymentMethodCollection or a ShippingTypeCollection.

Please add support for this.
Thank you.

**Comment by kharanenka** [comment]
Fixed in Toolbox plugin version 1.14.0
