### ISSUE TITLE
Issues after installing Properties for Shopoholic Plugin in octobercms

### ISSUE THREAD

**Issue by matthewborgcarr** [lovata/oc-shopaholic-plugin#105]
After installing this plugin: [Link](https://octobercms.com/plugin/lovata-propertiesshopaholic)

All the website went down and I am getting the following exception:

`Call to undefined method October\Rain\Foundation\Application::share()`

To be more specific there error is being generated in the following line:

 ```
* Register the service provider.
     *
     * @return void
     */
    public function register()
    {
        $this->app['cart'] = $this->app->share(function($app)
        {
            $storage = $app['session'];
            $events = $app['events'];
            $instanceName = 'cart';
            $session_key = '4yTlTDKu3oJOfzD';
```

Error:

`$this->app['cart'] = $this->app->share(function($app)`

And the file causing the error is the following:

**[pathToProject]/plugins/shahiemseymor/octocommerce/vendor/darryldecode/cart/src/Darryldecode/Cart/CartServiceProvider.php line 21**

Any suggestions?

Thanks a lot

**Comment by kharanenka** [comment]
Hi! This file is not from our plugins. In what file is this error?

**Comment by matthewborgcarr** [comment]
Hi and thank you very much for your comment.

So if this is not part of this plugin then it must be a conflict from another plugin :/

I've updated my issue with the link to the file causing the error...

Thanks again

**Comment by kharanenka** [comment]
Please try to temporarily remove the plugin from the project and check that error disappears.

**Comment by matthewborgcarr** [comment]
Noted with thanks. The problem is that I can't access the backend at the moment.

Trying to revert back my project hoping that the error disappears and I try re-installing the plugin once again.

**Comment by kharanenka** [comment]
I see that plugin has not been updated since May 26, 2015.
Have you updated OctoberCMS core?
This plugin is incompatible with current version of kernel, because version of laravel was changed.

**Comment by matthewborgcarr** [comment]
I confirm that the issue is coming from OctoCommerce plugin.

You were right... My apologies.

I will re-install Properties for Shopoholic and try again.

Thank you so much for your help and professional support

**Comment by kharanenka** [comment]
Thank you for your interest in our plugins. You can ask questions in slack channel.
