### ISSUE TITLE
Error since recent updates,

### ISSUE THREAD

**Issue by chrisvidal** [lovata/oc-shopaholic-plugin#106]
After updating with the last version, I got the error that blocks everything 
`
(1/1) FatalErrorExceptionClass 'Lovata\OrdersShopaholic\Classes\Helper\AbstractPaymentGateway' not found
--
in PaymentGateway.php (line 16)
`

**Comment by kharanenka** [comment]
Hi! OctoberCMS does not use $require parameter in Plugin.php, when updating components, so this error occurs.Please follow the next steps:
1. comment "extends AbstractPaymentGateway" in \Lovata\OmnipayShopaholic\Classes\Helper\PaymentGateway.php
2. Upadate plugins
3. Revert "extends AbstractPaymentGateway" in \Lovata\OmnipayShopaholic\Classes\Helper\PaymentGateway.php

**Comment by chrisvidal** [comment]
ok, got it, thanks
closing ticket
