### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by chrisvidal** [lovata/oc-shopaholic-plugin#107]
How do I get the list of orders for a user?
I didnt find any component for this
thanks

**Comment by kharanenka** [comment]
Hi @chrisvidal! You can find information in [documentation](https://github.com/lovata/oc-shopaholic-plugin/wiki/IntegrationWithUserPlugin)

If you have any more questions, you can ask in "shopaholic"  slack channel

**Comment by chrisvidal** [comment]
Thanks and Sorry I didnt see it in the doc.

**Comment by chrisvidal** [comment]
mmm sorry I cant find the way to write in  "shopaholic" slack channel

**Comment by chrisvidal** [comment]
is there a way to implement coupon and/or voucher concepts ?
