### ISSUE TITLE
Pagination count per page

### ISSUE THREAD

**Issue by chrisvidal** [lovata/oc-shopaholic-plugin#118]
Hi, 
it would be interesting to be able to control the property count_per_page for the Pagination component.

So we can offer the customer the choice of displaying 9 or 15 or all products.

Thanks

**Comment by kharanenka** [comment]
Hi @chrisvidal! We added processing of **"limit"** parameter for [Pagination](https://github.com/lovata/oc-toolbox-plugin/wiki/Components) component in [Toolbox](https://octobercms.com/plugin/lovata-toolbox) plugin. (version 1.17.0)
