### ISSUE TITLE
Prices showing no decimal places 

### ISSUE THREAD

**Issue by adarrel753** [lovata/oc-shopaholic-plugin#119]
Hi

I set the price of an offer to £49.99 but when the price is displayed it gets rounded to £50. How do I stop the automatic rounding?

**Comment by adarrel753** [comment]
It's ok I figured it out. I had to go to Settings...Misc...Application Settings...Price Format and set the number of decimal places to 2. It defaults to <blank>.

**Comment by kharanenka** [comment]
You are right, you had to set the price format in the settings
