### ISSUE TITLE
[Question] multiple properties in offers

### ISSUE THREAD

**Issue by chrisvidal** [lovata/oc-shopaholic-plugin#123]
Hi,

I bought the Properties plugin,
as my client is requiring multiple Properties for the offers.

He is asking if we can have 2 select dropdown (or radio button) to choose from and update the price accordingly.

For example, a jeans offer would have a Size and a Color properties.
Size: S, M, L, XL
Color: Blue, Black, Red
Each combination has his own price.

on the product page: 2 select dropdown, one to select the size and the other one to select the Color.
upon the choice of the size and the color, the price would be updated accordingly on the product page.

Are we able to do that please?

**Comment by kharanenka** [comment]
Hi @chrisvidal! Yes it is possible to do. We did a similar task. We need to show different prices for cans of paint with different colors and volumes.

1. You need to create offers for all possible combinations of colors and sizes.
2. You need to show 2 select with possible variants of properties. This will not be an easy task, but you will be able to do it. To do this, you'd better add dynamic methods where the data will be prepared.
3. If your design allows, it will be better if you make a step-by-step selection of values. For example, first color and then size.
4. You need to get offer ID by the selected combination of property values.

P.S. In our latest clothing project, we created products of different colors as related products. Switching between colors is link to new page. Perhaps this solution will suit you.

**Comment by chrisvidal** [comment]
thanks @kharanenka 

- [x] You need to create offers for all possible combinations of colors and sizes. => I did this indeed
- [ ] You need to show 2 select with possible variants of properties. This will not be an easy task, but you will be able to do it. To do this, you'd better add dynamic methods where the data will be prepared. => I have no clue about how to tackle this problem
- [x] If your design allows, it will be better if you make a step-by-step selection of values. For example, first color and then size. => it needs to be an independent choice from one each other
- [ ] You need to get offer ID by the selected combination of property values. => ok

**Comment by kharanenka** [comment]
Do you have an installed "Filters for Shopaholic" plugin in the project?

**Comment by kharanenka** [comment]
You need add method in [OfferCollection](https://github.com/lovata/oc-shopaholic-plugin/wiki/OfferCollection) class:

**Comment by kharanenka** [comment]
You need to add method in [OfferCollection](https://github.com/lovata/oc-shopaholic-plugin/wiki/OfferCollection) class:
You need to create property with code == 'color'
```php
\Lovata\Shopaholic\Classes\Collection\OfferCollection::extend(function ($obOfferList) {
    /** @var \Lovata\Shopaholic\Classes\Collection\OfferCollection $obOfferList */
    $obOfferList->addDynamicMethod('getColorList', function () use ($obOfferList) {
        $arResult = [];

        /** @var \Lovata\Shopaholic\Classes\Item\OfferItem $obOfferItem */
        foreach ($obOfferList as $obOfferItem) {
            $obPropertyValueList = $obOfferItem->property->getByCode('color');
            /** @var \Lovata\PropertiesShopaholic\Classes\Item\PropertyValueItem $obPropertyValueItem */
            foreach ($obPropertyValueList as $obPropertyValueItem) {
                $arResult[$obPropertyValueItem->slug] = $obPropertyValueItem->value;
            }
        }

        return $arResult;
    });
});
```
```twig
{% set obProduct = ProductPage,get() %}
{% set arColorList = obProduct.offer.getColorList() %}
<select name="color">
{% for sSlug, sVlaue in arColorList %}
    <option value="{{ sSlug }}">{{ sVlaue }}</option>
{% endfor %}
</select>
```

**Comment by chrisvidal** [comment]
Thanks so much @kharanenka 

I am trying to implement this code and facing an exception.

Trying to read the code:
```php
$obPropertyValueList = $obOfferItem->property->getByCode('color');
```

This does not return a list of property value. It returns a PropertyItem.
I double checked that I created a property with the code 'color'.
My property is of type "text input" Does it matter? Does it need to be of type "select"?

An exception is raised here:
ErrorException: Trying to get property 'slug' of non-object

```php
$arResult[$obPropertyValueItem->slug] = $obPropertyValueItem->value;
```

**Comment by kharanenka** [comment]
Sorry, it is my mistake.
```
\Lovata\Shopaholic\Classes\Collection\OfferCollection::extend(function ($obOfferList) {
    /** @var \Lovata\Shopaholic\Classes\Collection\OfferCollection $obOfferList */
    $obOfferList->addDynamicMethod('getColorList', function () use ($obOfferList) {
        $arResult = [];

        /** @var \Lovata\Shopaholic\Classes\Item\OfferItem $obOfferItem */
        foreach ($obOfferList as $obOfferItem) {
            $obPropertyItem = $obOfferItem->property->getByCode('color');
            if ($obPropertyItem->isEmpty() || $obPropertyItem->property_value->isEmpty()) {
                continue;
            }

            $obPropertyValueList = $obPropertyItem->property_value;

            /** @var \Lovata\PropertiesShopaholic\Classes\Item\PropertyValueItem $obPropertyValueItem */
            foreach ($obPropertyValueList as $obPropertyValueItem) {
                $arResult[$obPropertyValueItem->slug] = $obPropertyValueItem->value;
            }
        }

        return $arResult;
    });
});
```

**Comment by kharanenka** [comment]
Did you create "color" property and set its value in offers?

**Comment by chrisvidal** [comment]
yes I did. 
I have a property named 'color' with the code 'color' defined as a input text. (not a select)
I have a product with 6 offers (combination of color and size properties) with the color filled in with different values.

**Comment by kharanenka** [comment]
Please try to clear cache
```
php artisan cache:clear
```

**Comment by kharanenka** [comment]
What getIDList() method returns?
```
$obOfferItem->property->getIDList();
```

**Comment by chrisvidal** [comment]
it returns an exception:

`ErrorException: array_values() expects parameter 1 to be array, null given in /oc-e/plugins/lovata/toolbox/classes/collection/ElementCollection.php:97`

**Comment by kharanenka** [comment]
Can you send dump of shopaholic* tables on a.khoronenko@lovata.com email?

**Comment by chrisvidal** [comment]
ok, email sent.
Thanks @kharanenka

**Comment by kharanenka** [comment]
You have property "color" with ID 10, but value of "code" field is 10655 for it. Please fix it and try again

**Comment by chrisvidal** [comment]
I am using the property ID 5 and not the ID 10;
the ID 5 has the proper code

**Comment by kharanenka** [comment]
You have property "Colour 1" with ID 5, but value of "code" field is "code" for it.
You need change "code" field value from "code" to "color".

**Comment by kharanenka** [comment]
Do you still have questions about this issue?

**Comment by kharanenka** [comment]
I changed "code" field value for "Colour 1" property
![_019](https://user-images.githubusercontent.com/18258760/47675310-a43ae500-dbca-11e8-90c6-22f6588056a9.png)
I got the following result
![_020](https://user-images.githubusercontent.com/18258760/47675449-0a276c80-dbcb-11e8-9a6b-8dcb5a04bab8.png)

**Comment by chrisvidal** [comment]
Thanks.

I am trying to add a dynamic method who will return all the filled-in value
property of an offer to have this:
[
  "Size" => [ "Small", "Medium", "Large"],
  "Color" => [ "Red", "Blue", "Black"]
]

It looks like something that the Filter plugin would do already?
Except that I am needing this for only one product, only the property that
concerns the product viewed in the page.

Would it easier to use something existing form the Filter plugin or
creating my own dynamic method based on the one you did for me yesterday?

Thanks

**Comment by kharanenka** [comment]
So that you get a list of available property values, you'd better use dynamic methods. 
I would recommend that you get property values by separate methods so that you can use them in the future. For example, you will need to update the list of sizes if the user chose a color.

**Comment by kharanenka** [comment]
Do you want to be able to customize it in backend?

**Comment by chrisvidal** [comment]
customize as in? I dont see what you mean

**Comment by kharanenka** [comment]
The site administrator should be able to set the list of properties that will be visible on the product page depending on the product category?

**Comment by chrisvidal** [comment]
we already have that when you attached a property set to a category.
the list of offer of a product then will inherit this list of available properties

**Comment by kharanenka** [comment]
I understand you correctly that all properties of the offers should participate in the choice?

**Comment by chrisvidal** [comment]
all the **filled-in** (not empty) properties of the offers should participate in the choices, yes

**Comment by kharanenka** [comment]
I understood, then there are 2 solutions:
1. Upgrade dynamic method
2. Use Filter plugin.

Both options are valid. In the case of using Filter plugin, you can easily make mutually exclusive options.

**Comment by chrisvidal** [comment]
I am working on the method one. ref. code below.

I am using the Filter Plugin, I am curious how I could use it to make this exclusive options.

in a ProductModelHandler, provide a general mothod returning an array of callable method for each property not-empty in all the offers of this product
```php
/** @var \Lovata\Shopaholic\Classes\Collection\OfferCollection $obOfferList */
        $obProductItem->addDynamicMethod('getOptionsList', function () use ($obProductItem) {

            $obOfferList = $obProductItem->offer;

            $arResult = [];

            foreach ($obOfferList as $obOfferItem) {

                $obPropertyList = $obOfferItem->property;

                foreach ($obPropertyList as $obPropertyItem) {

                    $obPropertyValueList = $obPropertyItem->property_value;

                    if (!$obPropertyValueList->isEmpty()) {

                         if (!array_key_exists($obPropertyItem->slug, $arResult)) {
                            $methodName = 'get'. studly_case($obPropertyItem->slug).'List';
                            $arResult[$obPropertyItem->slug] = $methodName;
                            $this->addPropertyValueListMethod($obProductItem, $obOfferList, $methodName, $obPropertyItem);
                        }

                    }
                }

            }

            return $arResult;

        });
```

then create the dynamic method returning the value for all the offers of a product for a property

```php
protected function addPropertyValueListMethod($obProductItem, $obOfferList, $methodName, $obPropertyItem)
    {

        $obProductItem->addDynamicMethod($methodName, function () use ($obProductItem, $obOfferList, $obPropertyItem) {

           $arResult = [];

            /** @var \Lovata\Shopaholic\Classes\Item\OfferItem $obOfferItem */
            foreach ($obOfferList as $obOfferItem) {
                $obPropertyItem = $obOfferItem->property->getByCode($obPropertyItem->slug);

                if ($obPropertyItem->isEmpty() || $obPropertyItem->property_value->isEmpty()) {
                    continue;
                }

                $obPropertyValueList = $obPropertyItem->property_value;
                /** @var \Lovata\PropertiesShopaholic\Classes\Item\PropertyValueItem $obPropertyValueItem */
                foreach ($obPropertyValueList as $obPropertyValueItem) {
                    $arResult[$obPropertyValueItem->slug] = $obPropertyValueItem->value;
                }
            }

            return $arResult;
        });

    }
```

**Comment by chrisvidal** [comment]
then in the product info partial,  this display all the select choice possible for the properties of all of the offers of a product

```twig
        {% set arOptionsMethodList = obProduct.getOptionsList() %}
        {% for sSlug, sMethodName in arOptionsMethodList %}
            {% set arColorList = attribute(obProduct, sMethodName) %}
            <select name="{{ sSlug }}">
            {% for sSlugItem, sValue in arColorList %}
                <option value="{{ sSlugItem }}">{{ sValue }}</option>
            {% endfor %}
            </select>
        {% endfor %}
```

**Comment by chrisvidal** [comment]
but still a lot to do:
- being able to retrieve an offer from a choice combination is a tough one (to update the price and to get the offer Id to add to the cart)

**Comment by kharanenka** [comment]
> but still a lot to do:
> 
> * being able to retrieve an offer from a choice combination is a tough one (to update the price and to get the offer Id to add to the cart)

You can use [filterByProperty](https://github.com/lovata/oc-shopaholic-plugin/wiki/OfferCollection#filterbypropertyarfilterlist-obpropertylist) method.

You can cut the code that was already written using the [FilterPanel](https://github.com/lovata/oc-shopaholic-plugin/wiki/FilterPanel) component, getOfferPropertyList method.
```
{% set obProduct = ProductPage.get() %}

{# Get products proeprty list for property sets with code 'main', enabled how filters #}
{% set obPropertyList = FilterPanel.getOfferPropertyList(['main'], null, obProduct.offer) %}
...
{# Render filter panel #}
```

**Comment by chrisvidal** [comment]
Thanks @kharanenka 

it looks interesting.


I had a try with that and it returns an empty collection
```
{% set obPropertyList = FilterPanel.getOfferPropertyList(['main'], null, obProduct.offer) %}
```

my guess is that it is because of the null parameter, where it seems to expect a $obPropertyList (or a ProductCollection not sure about the code and comment in the FilterPanel component)

**Comment by kharanenka** [comment]
Maybe you need to make additional configuration of properties: enable them as a filter and bind them to the group "main".

**Comment by chrisvidal** [comment]
oh ok got it.

just did it.

With Color, it works fine and I can see the select dropdown but not with
the Size property (attached to the same set)

**Comment by kharanenka** [comment]
Have you configured "size" property as well as "Color" property?

**Comment by chrisvidal** [comment]
yes same way

**Comment by kharanenka** [comment]
it works fine
```
{% set obPropertyList = FilterPanel.getOfferPropertyList(['main'], null, obProduct.offer) %}
{% for obProperty in obPropertyList %}
    {{ obProperty.name }}
    <select name="{{ obProperty.code }}">
        {% for obPropertyValue in obProperty.property_value %}
        <option value="{{ obPropertyValue.slug }}">{{ obPropertyValue.value }}</option>
        {% endfor %}
    </select>
{% endfor %}
```
Result:
```
<select name="size">
                <option value="small">Small</option>
                <option value="medium">Medium</option>
                <option value="large">Large</option>
            </select>
    Colour 1
    <select name="color">
                <option value="blue">Blue</option>
                <option value="black">Black</option>
                <option value="red">Red</option>
            </select>
```

**Comment by chrisvidal** [comment]
I reset my data set and it works fine now

thanks

**Comment by chrisvidal** [comment]
how would you suggest from here, to get the update price and offer from the
choice combination?

**Comment by kharanenka** [comment]
You must send ajax request. You can use the [filterByProperty](https://github.com/lovata/oc-shopaholic-plugin/wiki/OfferCollection#filterbypropertyarfilterlist-obpropertylist) method to get a suitable offer.

**Comment by chrisvidal** [comment]
I am just back from some long weekend holiday. 
Hence I didnt get a chance to look into it yet.
I will try to use the filterByProperty method as recommended, it sounds good to me.
I will open a new thread if I need more details.
Thanks @kharanenka

**Comment by skacco** [comment]
Hello could you help me with the ajax request? I have the same problem and I need the code to complete the ajax request, get the price, and select the correct trade offer.

**Comment by kharanenka** [comment]
Hi @skacco! Please create new issue with full description
