### ISSUE TITLE
PROMO Page in Backend not showing for non-owners / non-superusers

### ISSUE THREAD

**Issue by kosmonowt** [lovata/oc-shopaholic-plugin#133]
Hi, we have an urgent problem:

Our customer needs to manage the Promo Section of the page, their rights are the following:
![Uploading Bildschirmfoto 2018-11-21 um 18.59.41.png…](Rights)

Anyhow there is no Promo Section showing here:
![Uploading IMG_0854.JPG…](BUG)

Here is what it looks like as superuser:
![Uploading 56451609912__6CC24561-2BD2-4297-A6F2-AE4460F05976.JPG…](Superuser View)

I hope you can fix it quickly.

**Comment by kharanenka** [comment]
Fixed in version 1.19.1
