### ISSUE TITLE
Properties associated to additional categories do not appear in product page in backend

### ISSUE THREAD

**Issue by pikanji** [lovata/oc-shopaholic-plugin#137]
A property field defined by Properties for Shopaholic feature is not displayed in a product's edit screen in backend, when the category associated with the property is set as an additional category.
The field is displayed as expected when the associated category is set to the product's category instead of additional category.

**Comment by kharanenka** [comment]
Hi! I think that this is the correct behavior. So it was conceived. What task are you going to solve with properties from additional category?

**Comment by pikanji** [comment]
@kharanenka I just wanted to set a category associated with properties to additional category, and I felt it natural to do that. I think this limitation is prone to misconfiguration by site administrator, and usage of categories is not really intuitive.
Unless he knows that the property is applied only with category but not additional categories, it would be really easy to mistakenly set categories associated with properties to additional categories.

For example, let's say I want all products to have properties A and B.
I would create "All product" category and associate properties A and B, and set this to product's category field.
However, I think administrators would be attracted to set "All product" category to additional categories and set its real category to category field, because it looks natural, and moreover, the one in the category field is the one that appears in the list page. So, when I want to add the same properties to all products, the category appears in the product list will all be the same.

**Comment by kharanenka** [comment]
If an administrator needs to set properties for all categories of products, then it will be enough for him to create a set of properties and attach it to all categories.

We have [issue](https://github.com/lovata/oc-shopaholic-plugin/issues/57) to add "global" field to property set. This will allow you to add properties to all products without attachment with categories.

**Comment by kharanenka** [comment]
Added "is_global" flag in PropertySet model.
Version of Properties for Shopaholic plugin - 1.8.0
