### ISSUE TITLE
[Coupons for shopaholic] Sorting coupons on usage count gives error

### ISSUE THREAD

**Issue by vosco88** [lovata/oc-shopaholic-plugin#140]
When sorting coupons on backend on usage count I get this error:

`"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'total_usage' in 'order clause' (SQL: select `lovata_coupons_shopaholic_coupons`.*, (select email from `users` where `lovata_coupons_shopaholic_coupons`.`user_id` = `users`.`id`) as `user_email` from `lovata_coupons_shopaholic_coupons` where `lovata_coupons_shopaholic_coupons`.`group_id` = 1 and `lovata_coupons_shopaholic_coupons`.`group_id` is not null order by `total_usage` desc limit 20 offset 0)" on line 664 of C:\laragon\www\tmavaochutnavka\vendor\laravel\framework\src\Illuminate\Database\Connection.php`

**Comment by kharanenka** [comment]
Fixed in 1.0.2 version
