### ISSUE TITLE
Products not showing in frontend.

### ISSUE THREAD

**Issue by Toinouco** [lovata/oc-shopaholic-plugin#15]
After populating products list and categories list in the backend, I cannot get to see anything in the frontend though I inserted code from the component in the page. Is there a bug or something I didn't see? Thank you for your answer.

**Comment by kharanenka** [comment]
Let's look at Example 1 for the [ProductList](https://github.com/lovata/oc-shopaholic-plugin/wiki/ProductList) component in more detail.

We use the [CategoryPage](https://github.com/lovata/oc-shopaholic-plugin/wiki/CategoryPage) component to obtain a category by the parameter :slug in the URL.
```twig
{% set obCategory = CategoryPage.get() %}
```
To test the operation of this component, you need to perform the following steps:
  1. Create new category in backend (for example: name = Samsung, slug = samsung)
  2. Activate new category in backend
  3. Create new page. Add components CategoryPage and ProductList on the page.
```twig
title = "Catalog"
url = "/catalog/:slug"

[CategoryPage]
slug = "{{ :slug }}"
slug_required = 1

[ProductList]
sorting = "no"
```

To display the goods and check the operation of the Product component, you need to perform the following steps:
  1. Crete new product in backend.
  2. Activate new product in backend.
  3. If you enable the setting "When you receive a list of active products, check for active offers" in Shopaholic settings, you need to create one active offer for the product.
  4. Attach the product to the category "Samsung".
  5. Go to the URL  http://yoursite.loc/catalog/samsung

We use the [ProductList](https://github.com/lovata/oc-shopaholic-plugin/wiki/ProductList) component to obtain a [ProductCollection](https://github.com/lovata/oc-shopaholic-plugin/wiki/ProductCollection) class object. Next, we work with the [ProductCollection](https://github.com/lovata/oc-shopaholic-plugin/wiki/ProductCollection) class object,  call methods:
  1. sort(ProductList.getSorting()) - apply sorting. Get sorting value from component settings 
  2. active() - apply filter by flag "active"
  3. category(obCategory.id) - apply filter by category ID. We got the [CategoryItem](https://github.com/lovata/oc-shopaholic-plugin/wiki/CategoryItem) class object from the [CategoryPage](https://github.com/lovata/oc-shopaholic-plugin/wiki/CategoryPage) component before.

```twig
{% set obProductList = ProductList.make().sort(ProductList.getSorting()).active().category(obCategory.id) %}
```
You can remove unnecessary methods from the chain or add other methods.

Example (Get 5 random active products):
```twig
{% set arProductList = ProductList.make().active().random(5) %}
```

**Full page code**:
```twig
title = "catalog"
url = "/catalog/:slug"
is_hidden = 0

[CategoryPage]
slug = "{{ :slug }}"
slug_required = 1

[ProductList]
sorting = "no"
==

{% set obCategory = CategoryPage.get() %}

{% set obProductList = ProductList.make().sort(ProductList.getSorting()).active().category(obCategory.id) %}
{% if obProductList.isNotEmpty() %}
    <div class="product-list-wrapper">
        {% for obProduct in obProductList %}
            <div data-id="{{ obProduct.id }}">
                <h1>{{ obProduct.name }}</h1>
                {% if obProduct.preview_image is not empty %}
                    <img src="{{ obProduct.preview_image.path }}" title="{{ obProduct.preview_image.title }}" alt="{{ obProduct.preview_image.alt }}">
                {% endif %}
                <div>{{ obProduct.preview_text }}</div>
            </div>
        {% endfor %}
    </div>
{% endif %}
```
