### ISSUE TITLE
Applying filter for both products and offers

### ISSUE THREAD

**Issue by gaabora** [lovata/oc-shopaholic-plugin#150]
Hi.

I want to implement filter for product and offer properties on the same page\panel.

Current code example (works fine for product props only)

    function onStart() {

        $obCategory = $this->CategoryPage->get();
        $arBreadcrumbs = $this->CatalogBreadcrumbs->getByCategoryID($obCategory->id);

        # taking props of all products and offers in category for filter panel
        $obAllProductList = $this->ProductList->make()->category($obCategory->id)->active();
        $obProductPropertyList = $this->FilterPanel->getProductPropertyList($this->param('slug'), $obAllProductList);
        $obOfferPropertyList = $this->FilterPanel->getOfferPropertyList($this->param('slug'), $obAllProductList);

        # product list to show with applied filters (if is)
        $obProductList = $this->ProductList->make()->category($obCategory->id)->active();

        # getting and formatting filter props\values from query string
        $arFilterList = [];
        foreach($obProductPropertyList as $obPropertyItem) {
            $slug = $obProductPropertyList->find($obPropertyItem->id)->slug;
            if (input($slug) !== null) $arFilterList[ $obPropertyItem->id ] = input($slug);
        }

        $obProductList->filterByProperty($arFilterList, $obProductPropertyList);
    #...

[Wiki says](https://github.com/lovata/oc-shopaholic-plugin/wiki/ProductCollection#filterbypropertyarfilterlist-obpropertylist-obofferlist--null)
...
filterByProperty($arFilterList, $obPropertyList, $obOfferList = null)
    $obOfferList - object OfferCollection - filtered offer collection. Only these offers will be involved in filtering of products.
...

but how do I get all offers for any product in selected category to filter them first and inject there?

**Comment by gaabora** [comment]
Thanks!
Offer collection was successfully filtered.
But now injecting $obOfferCollection to product's collection filterByProperty doesn't take any effect
both
$obProductList->filterByProperty($arProductFilterList, $obProductPropertyList,);
$obProductList->filterByProperty($arProductFilterList, $obProductPropertyList, $obOfferCollection);
return same result

	function onStart() {

		$obCategory = $this->CategoryPage->get();
		$arBreadcrumbs = $this->CatalogBreadcrumbs->getByCategoryID($obCategory->id);

		# taking props of all products and offers in category for filter panel
		$obAllProductList = \Lovata\Shopaholic\Classes\Collection\ProductCollection::make()->category($obCategory->id)->active();

		$obProductPropertyList = $this->FilterPanel->getProductPropertyList($this->param('slug'), $obAllProductList);
		$obOfferPropertyList = $this->FilterPanel->getOfferPropertyList($this->param('slug'), $obAllProductList);

		# product list to show with applied filters (if is)
		$obProductList = \Lovata\Shopaholic\Classes\Collection\ProductCollection::make()->category($obCategory->id)->active();

		# getting and formatting filter props\values from query string
		$arOfferFilterList = [];
		foreach($obOfferPropertyList as $obPropertyItem) {
			$slug = $obOfferPropertyList->find($obPropertyItem->id)->slug;
			if (input($slug) !== null) $arOfferFilterList[ $obPropertyItem->id ] = input($slug);
		}
		

		$obOfferCollection = \Lovata\Shopaholic\Classes\Collection\OfferCollection::make()->active();
		$obOfferCollection->filterByProperty($arOfferFilterList, $obOfferPropertyList);
		
		dump($obOfferCollection);

		$arProductFilterList = [];
		foreach($obProductPropertyList as $obPropertyItem) {
			$slug = $obProductPropertyList->find($obPropertyItem->id)->slug;
			if (input($slug) !== null) $arProductFilterList[ $obPropertyItem->id ] = input($slug);
		}

		$obProductList->filterByProperty($arProductFilterList, $obProductPropertyList, $obOfferCollection);

		dd($obProductList);

output

	OfferCollection {#1223 ▼
	  #iPosition: 0
	  #arElementIDList: array:1 [▼
		6 => 75 // filtered
	  ]
	  #iSkip: 0
	  +implement: null
	  #extensionData: array:4 [▶]
	}

	ProductCollection {#1204 ▼
	  #iPosition: 0
	  #arElementIDList: array:4 [▼
		0 => 22
		1 => 23
		2 => 24 // only this product has order id=75
		3 => 25
	  ]
	  #iSkip: 0
	  +implement: null
	  #extensionData: array:4 [▶]
	}

**Comment by kharanenka** [comment]
Hi! You need to fix:
```php
function onStart() {

	$obCategory = $this->CategoryPage->get();
        $arBreadcrumbs = $this->CatalogBreadcrumbs->getByCategoryID($obCategory->id);

        # taking props of all products and offers in category for filter panel
        $obAllProductList = \Lovata\Shopaholic\Classes\Collection\ProductCollection::make()->category($obCategory->id)->active();

        $obProductPropertyList = $this->FilterPanel->getProductPropertyList($this->param('slug'), $obAllProductList);
        $obOfferPropertyList = $this->FilterPanel->getOfferPropertyList($this->param('slug'), $obAllProductList);

        # product list to show with applied filters (if is)
        $obProductList = \Lovata\Shopaholic\Classes\Collection\ProductCollection::make()->category($obCategory->id)->active();

        # getting and formatting filter props\values from query string
        $arOfferFilterList = [];
        foreach($obOfferPropertyList as $obPropertyItem) {
            $slug = $obOfferPropertyList->find($obPropertyItem->id)->slug;
            if (input($slug) !== null) $arOfferFilterList[ $obPropertyItem->id ] = input($slug);
        }

        $arProductFilterList = [];
        foreach($obProductPropertyList as $obPropertyItem) {
            $slug = $obProductPropertyList->find($obPropertyItem->id)->slug;
            if (input($slug) !== null) $arProductFilterList[ $obPropertyItem->id ] = input($slug);
        }

        $obProductList->filterByProperty($arProductFilterList, $obProductPropertyList)->filterByProperty($arOfferFilterList, $obOfferPropertyList);

        dd($obProductList);
```

**Comment by gaabora** [comment]
Thanks! Now it works like intended. I think it needs to be in the documentation.

**Comment by kharanenka** [comment]
Our priority now is update of documentation and transfer to separate site.

**Comment by gaabora** [comment]
> update of documentation

When?
