### ISSUE TITLE
Plugin compatibility

### ISSUE THREAD

**Issue by SusValiente** [lovata/oc-shopaholic-plugin#151]
Hello, i'm really interested in trying this plugin in my website, but before that, I would like to know if it is mandatory to have installed the Shopaholic theme. In other words, I just want to know if the plugin is compatible with my custom theme.
Thanks

**Comment by kharanenka** [comment]
Hi! 
Our plugins do not contain default templates. They contain only logic for render data in template. Shopaholic theme is absolutely not necessary to install plugins. You can use it as an example.

This is one of the main differences between Shopaholic plugin and other solutions that are in the marketplace.
