### ISSUE TITLE
Language labels wrong or missing

### ISSUE THREAD

**Issue by mjauvin** [lovata/oc-shopaholic-plugin#157]
In the latest update to Shopaholic, the "Taxes" tab under CATALOG CONFIGURATION settings page has invalid labels for those new settings (see screenshot attached)

![screenshot from 2019-02-27 11-00-01](https://user-images.githubusercontent.com/2013630/53503826-d9731900-3a7e-11e9-8397-19cd4edf15ef.png)

**Comment by kharanenka** [comment]
Fixed in version 1.21.1
