### ISSUE TITLE
Omnipay Error

### ISSUE THREAD

**Issue by ODDCODE** [lovata/oc-shopaholic-plugin#16]
return;
        }
  
        //Get payment gateway list
        $arPaymentGatewayList = [];
  
        $arGatewayList = Omnipay::getFactory()->find();
        if (!empty($arGatewayList)) {
            foreach ($arGatewayList as $sGatewayName) {
                $arPaymentGatewayList[$sGatewayName] = $sGatewayName;
            }
        }

**Comment by kharanenka** [comment]
Hi!
Please check, if you follow the steps in the [update](https://octobercms.com/plugin/lovata-omnipayshopaholic) guide. Before you start using the ["Omnipay for Shopaholic"](https://octobercms.com/plugin/lovata-omnipayshopaholic) plugin, you need to install the [ignited/laravel-omnipay](https://github.com/ignited/laravel-omnipay) package and and omnipay gateway packages.

Thank you for your interest in our plugins!

**Comment by philmarc** [comment]
There is an error in your upgrade guide

`composer update ignited/laravel-omnipay`

should be 

`composer require ignited/laravel-omnipay`

**Comment by kharanenka** [comment]
fixed
