### ISSUE TITLE
After submitting cart the price of the offers is set to 0

### ISSUE THREAD

**Issue by vosco88** [lovata/oc-shopaholic-plugin#162]
This is a weird issue happening for me. After I submit the Cart using MakeOrder component with the form to submit. The price of the offers that were in the cart is set to 0 and subsequently also the order total price is set to 0. 

I did perform an update to a new version of the plugins, so now I do not know if that is a bug or I need to setup something somewhere for it to work. 

Edit:
I have managed to investigate a bit it happens in the `OfferOrderPositionProcessor ` function `decrementOfferQuantity()` and when I do this in the try catch 
`\Log::info($this->obOffer);
  $this->obOffer->save();
  \Log::info($this->obOffer);`

This is the output of the first log [https://codebeautify.org/jsonviewer/cb42e6c0](url)
This is the output of the second log [https://codebeautify.org/jsonviewer/cbe07afa](url)

Also when I turn off the automatic reduction of quantity everything works fine.

Thanks for the help

**Comment by kharanenka** [comment]
Fixed in 1.21.2 version of Shopaholic plugin
