### ISSUE TITLE
cannot clear text property values for non default language 

### ISSUE THREAD

**Issue by mjauvin** [lovata/oc-shopaholic-plugin#163]
For text/textarea type properties, if we clear a previously defined property value for a translation (not the default one), the value does not get updated in the database.

**Comment by mjauvin** [comment]
This is a very big issue for my project as well. Once a translation has been done, you cannot revert back to using the default language value for this language.

**Comment by kharanenka** [comment]
Fixed in version 1.8.1 of Properties for Shopaholic plugin
