### ISSUE TITLE
[PropertiesShopaholic] After update 1.8.2 didnt work import offers

### ISSUE THREAD

**Issue by Adsumushero** [lovata/oc-shopaholic-plugin#178]
Hello. After update properties (1.8.2 at 10 may 2019) stopped working offer import module. Product_id field disappeared from the right panel and now i catn bind my offers with product by external id.
![Screenshot_6](https://user-images.githubusercontent.com/29700783/57578515-38f69780-74b8-11e9-984e-64762ab3e6f9.jpg)

**Comment by Adsumushero** [comment]
Found a mistake.
Open plugins/lovata/propertiesshopaholic/classes/event/offer/ExtendOfferControllerHandler.php
Finde `$arConfig = (array)$obController->makeConfig('$/lovata/shopaholic/controllers/product/config_import_export.yaml');`
Replace `$arConfig = (array)$obController->makeConfig('$/lovata/shopaholic/controllers/offers/config_import_export.yaml');`

**Comment by kharanenka** [comment]
Hi! Bug fixed in 1.8.3 version.
Thanks for your contribution
