### ISSUE TITLE
Class 'Lovata\Toolbox\Classes\Event\ModelHandler' not found

### ISSUE THREAD

**Issue by AxDSan** [lovata/oc-shopaholic-plugin#18]
![](https://my.mixtape.moe/igszfx.png)

I was just installing this along with 2 more plugins, User and User Extender and Flat UI theme.

I redo the installation and the previous `install_log.txt` got overwritten and it wasn't that helpful after all..

**Comment by kharanenka** [comment]
Hi!
The [Shopaholic](http://octobercms.com/plugin/lovata-shopaholic) plugin requires the installation of the [Toolbox](http://octobercms.com/plugin/lovata-toolbox) plugin. Please check, if the [Toolbox](http://octobercms.com/plugin/lovata-toolbox) plugin is installed.

Thank you for your interest in our plugins!

**Comment by AxDSan** [comment]
Thank you very much, Didn't noticed it required Toolbox! My bad! Thanks for  the support!
