### ISSUE TITLE
How to make Child Categories?

### ISSUE THREAD

**Issue by AxDSan** [lovata/oc-shopaholic-plugin#19]
Example: 
- Weapons `Main Category`
  - Rifles `Child`
  - Knives `Child`
  - Shotguns `Child`

I see that the example code you provided for `CategoryList` it's supported:
![](https://my.mixtape.moe/yhqbuz.png)

How could I achieve that?

**Comment by kharanenka** [comment]
Hi!
We added [step-3](https://github.com/lovata/oc-shopaholic-plugin/wiki/Step-3-Render-Catalog-Menu) to the quick start guide. It shows how to render the category tree.

Thank you that you continue to be interested in our plugins!

**Comment by AxDSan** [comment]
Thank you for making this amazing plugin :D - Definitely reduces time :D

**Comment by AxDSan** [comment]
Seems weird but, I got this new issue where the list won't render completely...
![](https://my.mixtape.moe/tfexzo.png)

This is my rendered view:
![](https://my.mixtape.moe/uowryo.png)

This is my Category List (backend):
![](https://my.mixtape.moe/fgwwyc.png)

I Don't know what I'm doing wrong here, I also have removed the portion of the code which checks if there are any products in the respective categories, so the entire categorized list is supposed to render, even if there are no products available 👍
