### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by pvullioud** [lovata/oc-shopaholic-plugin#20]
on page : https://github.com/lovata/oc-shopaholic-plugin/wiki/PropertyItem
<img src="https://monosnap.com/file/dgNqh1sDr640D1qEQG3UZIoz8n1jbb.png">

**Comment by kharanenka** [comment]
Hi!

Errors in the documentation are fixed. In the coming days we will add to the quick start guide steps with a detailed description:
1. how to display the properties of products and offers
2. how to display the filtering panel
3. how to add filtering for the list of products

Thank you that you continue to be interested in our plugins!

**Comment by pvullioud** [comment]
Your welcome. if it's help
I'll continue to report issues and typo
My tests are good until now. I like what I'm seeing. Thanks for the good work
