### ISSUE TITLE
[Backend-Products-Offers] Update offer issue

### ISSUE THREAD

**Issue by pvullioud** [lovata/oc-shopaholic-plugin#21]
I got this error when I try to edit an existing offer.
<img src="https://monosnap.com/file/rbqZzTHs8u90stnjIGLk2XKbxsav8x.png">

**Comment by kharanenka** [comment]
Enable in your php.ini:
```
short_open_tag = On
```

**Comment by pvullioud** [comment]
October project follow PSR standard
http://www.php-fig.org/psr/psr-1
2.1. PHP Tags
PHP code MUST use the long <?php ?> tags or the short-echo <?= ?> tags; it MUST NOT use the other 
tag variations.

Could be better to fix the code.

**Comment by kharanenka** [comment]
Thank you for your issue, I agree with you. We will correct this error in the near future.

**Comment by kharanenka** [comment]
Fixed in version 1.2.1
