### ISSUE TITLE
Suggestion about storing offer price

### ISSUE THREAD

**Issue by riartem** [lovata/oc-shopaholic-plugin#27]
By the [OfferItem description](https://github.com/lovata/oc-shopaholic-plugin/wiki/OfferItem) I see that price stored as float value.

It may cause some issues in payments or calculations. 
Because (it just one possible case):
```
$a = 0.17;
$b = 1 - 0.83; //0.17
return ($a === $b ); // false
```

[Robert C. Martin](https://en.wikipedia.org/wiki/Robert_C._Martin) (approximate quote): "Use floating-point numbers to represent money amounts is almost a crime"

I think better practice to store it as integer in minimal unit of currency (cents for USD or kopeck for RUB-BYN — it does not matter). And convert it to floats right before displaying at frontend (depending on the 'decimals' setting). 
What do you think?

**Comment by kharanenka** [comment]
Hi! We decided not to change the storage of prices in the float format. We add rounding the numbers (0.1699999999 -> 1.17), when calculating prices.
