### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by chrisvidal** [lovata/oc-shopaholic-plugin#28]
Hi,
thanks for this amazing oc plugin.
I have several questions when looking at the wiki pages.
- I dont get the difference of usage between ProductData and ProductPage for example.
They both create a ProductItem.
- Is the ProductItem or ProductData  (Product model) cached somehow ? 
- do you have a basic OC theme that comes with this plugin?
- why did you decide to not implement the UI html inside the components ?
- why did you decide to somehow develop different layer above the model? for example, the model Product has a ProductItem to manage it. Why this architecture? What are the advantages? For my understanding :)

Thanks in advance

**Comment by riartem** [comment]
Interested in last two questions too..

**Comment by kharanenka** [comment]
Hi!
Thank you for your interest in our plugins!

1. We call components the same name, now there are 3 types:
    1. Component for the element page - *Page (ProductPage, CategoryPage). The components are used for pages with URLs **/ ... /:slug** on which to display the data of element or display the 404 page, if the element was not found in the database by **slug** parameter.
    2. A component for obtaining an object by ID - *Data (CategoryData, CategoryPage). Components are used in different situations. For example:
        * Display block with category on the index page. Category ID can be obtained from site settings.
        * Display in popup a detailed description of the product. We get a view of popup using the ajax query with the rendering of partial.
    3. Components for working with lists of elements - *List (ProductList, CategoryList)

2. Objects of *Item class (ProductItem, CategoryItem) are used for caching models and for convenient use of cached data.
3. We plan in the near future to make a demo site with an open repository and add a customizable theme to the marketplace.
4. Each site has its own design and its HTML structure. We do not want to impose our HTML structure on developers. We want to give developers an easy and convenient tool for website development. Our components can be used for different tasks. For example: component [ProductList](https://github.com/lovata/oc-shopaholic-plugin/wiki/ProductList) can be used to display a catalog of products (a classic task), for display on the index page of a block with random products (custom block). The component structure allows developers to write less code for custom blocks. The components return the objects of the classes *Item and *Collection. These classes are easily expanded (see the extension of the [item](https://github.com/lovata/oc-toolbox-plugin/wiki/ElementItem#extending) and the [collection](https://github.com/lovata/oc-toolbox-plugin/wiki/ElementCollection#extending) for more details)
5. We use an additional layer to cache the model data. We cache the finished array of model data. For convenient work with the cache, we added classes *Item (ProductItem, CategoryItem). They allow you to work with an array obtained from the cache, both with the model. Objects of the class are **easily expanded** ([see more](https://github.com/lovata/oc-toolbox-plugin/wiki/ElementItem#extending)). You can add new methods to them, add additional methods for preprocessing the attributes.

**Comment by riartem** [comment]
@kharanenka Thank you for detailed response!
I have complimentary question about extending. If the objects are **easily expanded**, why you need to hardcode some parts ([1](https://github.com/lovata/oc-shopaholic-plugin/blob/bd256489a0186892d5833a95a5e1c91ebfa228e2/classes/event/ProductModelHandler.php#L198), [2](https://github.com/lovata/oc-shopaholic-plugin/blob/bd256489a0186892d5833a95a5e1c91ebfa228e2/components/ProductList.php#L55)) of your own plugins in the main shop plugin?

**Comment by kharanenka** [comment]
@riartem We try to avoid such integration between plugins, but this does not always work out as we would like. Your examples refer to the classes of components and events. If we talk about objects of classes *Item or *Collection, then you will not find such hard integration.
