### ISSUE TITLE
How can implement product search

### ISSUE THREAD

**Issue by alvaro-canepa** [lovata/oc-shopaholic-plugin#32]
### Hi, first, great plugin !!!

I'm writing an ecommerce theme, and need to add search feature. Is there something already implemented for that?

Thanks

**Comment by kharanenka** [comment]
Hi!
We have a "Sphinx for Shopaholic" plugin to search by products and categories using the Sphinx. We have a "Search for Shopaholic" plugin to search by products and categories using simple search logic by database. Both plugins are ready for use, but for publication in the marketplace they need to be finalized and add a description to the wiki. One plugin can be replaced with another plugin, without any changes in the code. Your theme will work with any of these plugins. If your topic is not enough to publish only the search logic, we are ready to change the development priorities and publish search plugins in the near future.
