### ISSUE TITLE
Dates translation

### ISSUE THREAD

**Issue by amdad** [lovata/oc-shopaholic-plugin#39]
Hello, Shopaholic display dates only in English.
 
October support translated dates with Argon (Carbon extension).
https://github.com/octobercms/october/issues/1968

Translate plugin, can switch dates language by switching active lang. It was just fixed (not published yet) to bring back this function to work again. 
https://github.com/rainlab/translate-plugin/issues/338 
Solved here: https://github.com/rainlab/translate-plugin/issues/338#issuecomment-360985863

Please add this function to Shopaholic, date property from Properties plugin and other Shopaholic plugins. Maybe adding it to main plugin will resolve issue in all of them or maybe not. 

Thank you!

**Comment by kharanenka** [comment]
Hello! I correctly understand you, what do you suggest for properties of the date type that return the value of the property as an object of the Argon class?

**Comment by amdad** [comment]
Yes, but it's not done by using Argon class directly. Argon is incorporated in Carbon and creating date output process. Check Rainlab.Blog for example what exactly is needed. Do not overthink it or workaround. 

For example I add to product template {{ obProduct.created_at|date() }} to look if it will be translated. Nope.

Date property maybe will inherit this from parent plugin, or require the same changes. Anyway. Start from main Shopaholic plugin by taking example from Rainlab.Blog.  

--------------
PS. (BTW) Wouldn't be nice to have Publish date for a products by default? If I want for example publish some week later for some time. Or you think, custom dates should be taken from properties plugin. But what about DB query builder then? When I component ask for data only published_at (date).

**Comment by kharanenka** [comment]
If you use the published_at field for deferred publication of goods, then of course we need to add this field to the product table to be able to make queries to the database. In our projects we use the mechanism of deferred publication of articles only in the news plugin. We can transfer this logic to the Shopaholic plugin.

**Comment by amdad** [comment]
Even more important then differed publishing, will be Trash function. For removed products to be restored or permanently removed. 

https://octobercms.com/docs/database/traits#soft-deleting + filter on backend product list to show trashed.

Should I create new issue for every single proposal or rather one issue topic for discussing them?

When new plugins will be released? Any date spans for them? 

Related products for Shopaholic and Accessories for Shopaholic in first place,,, because they are simple.
I wait for almost every one of them :) Extension list for Shopaholic on October Marketplace is not the same as on Lovata website. I hope all of them are planned.

**Comment by kharanenka** [comment]
Models Product and Offer already use the trait SoftDelete. We just need to add control to the backend.

We can create a room in the official OctoberCMS slack chat and discuss the issues there, then transfer the result to github issues.

We almost finished the work on the demo site. This is a priority task for us now. After it, we will return to the release of plugins. We have developed many plugins. For them, only documentation is needed. The plugins "Related products for Shopaholic" and "Accessories for Shopaholic" will be released within 1-3 weeks.

**Comment by amdad** [comment]
Oh, I would be very grateful if you publish your demo code (even if it's unfinished) on Github now and commit changes later. All those JS and working functionality, will be much easier for me to get working orders and cart/order/payment etc.

**Comment by amdad** [comment]
OH THANK YOU VERY MUCH FOR PUBLISH DEMO REPOSITORY! 🤗 😀
