### ISSUE TITLE
Accessories plugin

### ISSUE THREAD

**Issue by amdad** [lovata/oc-shopaholic-plugin#41]
Hello, I wanted to ask for product accessories plugin.

Is there any chance to get unofficial release of it now, without waiting?

**Comment by kharanenka** [comment]
Hi! That is unnecessary. We send the product accessories plugin today for a moderation.

**Comment by amdad** [comment]
Nice! other plugins too? :)

**Comment by kharanenka** [comment]
3 plugins will be sent today:
  * Reviews for Shopaholic
  * Related products for Shopaholic
  * Accessories for Shopaholic

**Comment by amdad** [comment]
Yeah, so those which are in demo theme. What price for them?

**Comment by amdad** [comment]
Ding dong 🔔, check your mail :)
