### ISSUE TITLE
New install

### ISSUE THREAD

**Issue by remagalot** [lovata/oc-shopaholic-plugin#52]
Update failed

"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'popularity' in 'field list' (SQL: update `lovata_shopaholic_products` set `preview_text` = Preview text. Product: Knee Length Lace Insert Denim Shorts - Light Blue Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua., `description` = <p>Description text. Product: <strong>Knee Length Lace Insert Denim Shorts - Light Blue</strong></p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>, `popularity` = 361, `updated_at` = 2018-02-12 22:41:59 where `id` = 1)" on line 664 of /var/www

**Comment by kharanenka** [comment]
It is bug in product seeder of the demo site. Fixed
