### ISSUE TITLE
Custom properties for products

### ISSUE THREAD

**Issue by cjayx** [lovata/oc-shopaholic-plugin#53]
Although users and orders do have custom properties, it would be also great to have custom properties for products.

**Comment by lautsevich** [comment]
Hi! Thx for the interest in Shopaholic. Look at our [Properties for shopaholic](http://octobercms.com/plugin/lovata-propertiesshopaholic) plugin.

**Comment by kharanenka** [comment]
Yes, additional properties for products and offers can be found in the plugin "Properties for Shopaholic"
