### ISSUE TITLE
Ability to create global properties

### ISSUE THREAD

**Issue by mjauvin** [lovata/oc-shopaholic-plugin#57]
It would be very useful to be able to create a property accessible to all products, independant of its category.

**Comment by kharanenka** [comment]
We will have to duplicate the properties and filtering settings that are now available in the relation settings with the category. This will duplicate most of the logic for working with global properties, to display properties and filtering. When filtering by global properties, it may be difficult to achieve good performance with a large catalog of products. Perhaps we can add global properties after the plugin optimization of the "Filters for Shopaholic" plugin.

**Comment by mjauvin** [comment]
An alternative I found was to create a TOP category which will have the new Property and create all categories under this Parent category.

**Comment by kharanenka** [comment]
Fixed in version 1.3.0 Properties for Shopaholic plugin

**Comment by mjauvin** [comment]
What exactly was done here, I am using the demo and cannot see a "global" property.

**Comment by kharanenka** [comment]
I am sorry, I mix up issue.

Now you can create global property set and attach it to all categories. You can use it for render custom filter panel and render filter panel on different pages.

I can add checkbox "global" to PropertySet model. This will get list of properties from global property sets + property sets that are attached to category.

**Comment by xyng** [comment]
> I can add checkbox "global" to PropertySet model. This will get list of properties from global property sets + property sets that are attached to category.

As this issue is closed and referred to as a solution in #137 I'd like to know what its status is.
We really need this functionality but it does not seem to be in the current version.

Thanks!

**Comment by kharanenka** [comment]
Hi @xyng!

We are now focused on adding taxes and multicurrency in plugins. This is highest priority for us. These new features will be added in coming days. Your task has not been developed yet.

**Comment by xyng** [comment]
Hi @kharanenka,
thanks for your answer!

I suppose this issue should be re-opened then, to prevent further confusion? :-)

**Comment by kharanenka** [comment]
Added "is_global" flag in PropertySet model.
Version of Properties for Shopaholic plugin - 1.8.0
