### ISSUE TITLE
Ability to select images from the media library.

### ISSUE THREAD

**Issue by mjauvin** [lovata/oc-shopaholic-plugin#58]
When assigning featured/gallery images for brands/categories/products, we should be able to select from the media library.

Currently, we can only upload new images.

**Comment by kharanenka** [comment]
Hi! We chose this way of downloading files for several reasons:
1. Files are downloaded to the server with a random name. The manager shouldn't monitor file names. Often managers ignore the recommendations. Load files with the same name. Load files with incorrect names (for example: "product photo.png" - the file name contains a space).
2. If you delete a file in the backend, the file is automatically deleted on the server. You don't need to clean the server of garbage.
3. You can specify "alt" and "title" attributes for images. This is good for SEO.
4. You can resize images using the getThumb () function without installing additional plugins.

**Comment by mjauvin** [comment]
Sorry to reopen this, but can you elaborate on how to "specify alt and title attributes" for images assigned to Products, Brands, etc.?

**Comment by kharanenka** [comment]
Hi @mjauvin !
This is a default feature of OctoberCMS. After uploading image, you can click on it and see modal window with settings. There you can set the title and description parameters.
In the template you can use them as:

```php
<img src="{{ obProduct.preview_image.getPath() }}" alt="{{ obProduct.preview_image.description }}" title="{{ obProduct.preview_image.title }}">
```

**Comment by mjauvin** [comment]
Oh, I didn't realize that, thanks.
