### ISSUE TITLE
Sending additional properties in order from product form.

### ISSUE THREAD

**Issue by shustrya** [lovata/oc-shopaholic-plugin#64]
As example:
I need to send "spucy level" from the product form to the order.
Or send comment for product to the order.

**Comment by kharanenka** [comment]
Good idea. This possibility must be added to the "Orders for Shopaholic" plugin.

**Comment by shustrya** [comment]
Hello, Andrey!
AddOn!!!

Adding to the basket by unique number, not by product offer.
For example.
Order the same pizza with different "spucy level".

----
Добавление в корзину по уникальному номеру, а не по товарному предложению.
Например.
Заказать одинаковую пицу с разным уровнем остроты.

**Comment by kharanenka** [comment]
Hi!
I developing improvements for "Orders" plugin now. I prepare for release additional properties for order position. I testing it now.

Will this solve your problem now?

P.S.
I added ability to add custom types of order position. Now this is available only for Offer model . But in future I plan to add another position types: sets of products and gifts.

I plan to add ability to create catalog without product offers. But this may not appear soon.

**Comment by kharanenka** [comment]
Fixed in version 1.6.0
