### ISSUE TITLE
Is there a way to show "latest" products?

### ISSUE THREAD

**Issue by haralake** [lovata/oc-shopaholic-plugin#66]
Hi! I show in the demo theme how to show random products, but is there a way to display "latest" products? If there is, how can i do it?

**Comment by kharanenka** [comment]
Hi! Of course, you can easily do this:
```
{% set obProductList = ProductList.make().active().sort('new') %}
```
obProductList contains active "latest" products (see [more](https://github.com/lovata/oc-shopaholic-plugin/wiki/ProductCollection#sortssorting))

For example:
render 5 latest products
```
{% set obProductList = ProductList.make().active().sort('new').take(5) %}
{% for obProduct in obProductList %}
    {{ obProduct.name }}
{% endfor%}
```

**Comment by haralake** [comment]
Thank you ! I missed that in documentation..
