### ISSUE TITLE
When select paid delivery method, change total cost

### ISSUE THREAD

**Issue by xariketi** [lovata/oc-shopaholic-plugin#68]
Hello! I try to configure shopaholic plugin, and i also testing your demo theme. I noticed that if i create a  delivery method with extra cost ,and then try to select the paid delivery method on frontend ,the total cost remains the same. Is there a easy way to change the total cost when client select paid delivery method?

**Comment by kharanenka** [comment]
We have added a "price" field for the ShippingType model after the demo site release. The demo site does not support the processing of the shipping price on the order page now.

In the near future we will add functions for changing the price of the order (discounts, coupons, certificates). I think we will add with this update a lot of useful features for calculating the price and getting prices after changing the shipping method, discount value, coupons and certificates.

We are now focused on adding new features and plugins. After that, we will return to developing a demo site.

Thank you for your interest in our plugins!
