### ISSUE TITLE
Selling digital goods ?

### ISSUE THREAD

**Issue by daslicht** [lovata/oc-shopaholic-plugin#69]
Hi,
is it possible to sell digital downlads with Shopaholic ?

~ Marc

**Comment by kharanenka** [comment]
Hi! Now we do not have support for the sale of digital products. But we have a request to add this function ([issue](https://github.com/lovata/oc-shopaholic-plugin/issues/62)). You can describe your requirements in the issue or add something new.

**Comment by daslicht** [comment]
thank you !
