### ISSUE TITLE
Omnipay tutorial / help

### ISSUE THREAD

**Issue by philmarc** [lovata/oc-shopaholic-plugin#72]
I am trying to make the payment work, using the Omnipay for Shopaholic plugin. 
Everything works fine in my shop except for the payment.

I have added a payment gateway (paypal) in the administration (with username, password and signature)
Then I have done a composer update with `ignited/laravel-omnipay` and `omnipay/paypal`

I have used most of the demo app code that you provide here, with the ajax mode for `MakeOrder`

```
[MakeOrder]
mode = "ajax"
flash_on = 1
redirect_on = 1
redirect_page = "shop/order_success"
```

When I click the pay button, I am expecting to be redirected to PayPal for the payment, but I am just being redirected to the `order_success` page. 

Can you provide a demo or a tutorial for the payment with paypal? 

Maybe I have to do something here : ?

```
//Make order
$('body').on('submit', '._make_order_form', function (e) {

    e.preventDefault();
    $('._make_order_error').addClass('uk-hidden');

    var _this = $(e.currentTarget),
        data = {
            'order': {
                'payment_method_id': _this.find('input[name="payment_method_id"]:checked').val(),
                'shipping_type_id': _this.find('input[name="shipping_type_id"]:checked').val(),
                'property': {
                    'address': _this.find('input[name="address"]').val()
                }
            },
            'user': {
                'name': _this.find('input[name="name"]').val(),
                'last_name': _this.find('input[name="last_name"]').val(),
                'email': _this.find('input[name="email"]').val(),
                'phone': _this.find('input[name="phone"]').val()
            }
        };

    $.request('MakeOrder::onCreate', {
        data: data,
        update: {
            'cart/cart_item_list': '._cart_item_list'
        },
        complete: function (response) {

            var data = response.responseJSON;
            if(data.status) {
                return;
            }

            $('._make_order_error p').html(data.message);
            $('._make_order_error').removeClass('uk-hidden');
        }
    });
});
```

_PS : Shopaholic is a great plugin so far, much better than the JKShop, which I deleted. Great job!_

**Comment by kharanenka** [comment]
Hi! You need to use the sendPaymentGateway () method in the OrderPage component.
It uses the package API (see [more](https://github.com/ignited/laravel-omnipay#usage)).
The method returns the gateway response:
```php
$obResponse = $obGateway->purchase($arGatewayData)->send();
return $obResponse;
```
If you use PayPal, then the method should return the redirect object to the PayPal page.

Perhaps you will need to add your own logic for full integration with the payment system.
We will be happy if you contribute methods for full integration.

**Comment by kharanenka** [comment]
Thank you for your interest in our plugins!
