### ISSUE TITLE
Error Creating Payment Method

### ISSUE THREAD

**Issue by thesigae** [lovata/oc-shopaholic-plugin#78]
Getting this after installing the plugin omnipay for shopaholic. 

```
 Error

We're sorry, but an unhandled error occurred. Please see the details below.

Class 'Omnipay\Omnipay' not found
/home/deltarv/dev.deltarv.biz/dev/october/plugins/lovata/omnipayshopaholic/classes/event/ExtendFieldHandler.php line 46

            return;
        }
  
        //Get payment gateway list
        $arPaymentGatewayList = [];
  
        $arGatewayList = Omnipay::getFactory()->find();
        if (!empty($arGatewayList)) {
            foreach ($arGatewayList as $sGatewayName) {
                $arPaymentGatewayList[$sGatewayName] = $sGatewayName;
            }
        }
```

**Comment by kharanenka** [comment]
Dublication - https://github.com/lovata/oc-shopaholic-plugin/issues/16

**Comment by thesigae** [comment]
@kharanenka 

Could you create documentation / video on installing omnipay after installing octobercms? I tried to create a composer.json with the listed dependencies which didn't work. 

Would love to use this plugin but can't when it doesn't work.

**Comment by thesigae** [comment]
@kharanenka 

Thank you for responding but where in the octobercms directory is this found? 

There is no composer.json at the root.

![image](https://user-images.githubusercontent.com/20378254/39545944-9e87c4ee-4e07-11e8-9554-2fd43838f24e.png)

But in my modules > system there is.

![image](https://user-images.githubusercontent.com/20378254/39546051-ef316e40-4e07-11e8-88c6-9783da8b23ae.png)

What do you mean, "You can create a relation between the payment method and the payment gateway" ???

**Comment by thesigae** [comment]
So here is what I am gathering and did:

I created the composer.json in the plugins folder. Ran **composer install** and **created a folder called omnipay in the vendor folder** which has all the omnipay plugins. 

Going to payment methods still causes the error as before. How do I tell omnipay plugin to use the folder vendor .

![image](https://user-images.githubusercontent.com/20378254/39726249-556d9626-5203-11e8-9563-0abb3dbe1997.png)

![image](https://user-images.githubusercontent.com/20378254/39726546-3e8d2290-5204-11e8-8cdd-8802c2da2bfe.png)

**Comment by kharanenka** [comment]
Hi! For example path to plugin folder is 'plugins/lovata/omnipayshopaholic' or 'plugins/author/myplugin'. See [more](http://octobercms.com/docs/plugin/registration#introduction) in OctoberCMS documentation.

**Comment by thesigae** [comment]
![image](https://user-images.githubusercontent.com/20378254/40382991-912ca5aa-5db4-11e8-82ee-17813e86bd11.png)

I still haven't solved this... DO I need to do anything with this to connect with the downloaded files from running the composer.json? Where do I put the example path?

**Comment by cdarken** [comment]
Could this be because Omnipay::getFactory() returns an instance of `Omnipay\Common\GatewayFactory` that has not a method called `find()`? I can only see a method `all()`. After I modified the line above if to call `all()` it worked.
