### ISSUE TITLE
Cart::onAdd updates with the input instead of adding to  cart

### ISSUE THREAD

**Issue by vosco88** [lovata/oc-shopaholic-plugin#80]
When I use Cart::onAdd same way as in documentation:
I add quantity = 5 with offer id = 1 - 5 items get added
as a next step
I add quantity = 3 with offer id = 1 - there are now 3 items with offer_id = 1 when I would expect it would be 5+3

Thanks for any help.

**Comment by kharanenka** [comment]
Hi! 
The onAdd() method allows you to create new position in user`s cart.
The onUpdate() method always overwrites the quantity.
You need send new quantity value and use onUpdate() method

**Comment by HEAD-MAN** [comment]
How should I implement "Add to cart" button which add one product to cart position if it already exists in cart? Should I store quantity of added to cart position on catalog page for each product? 
Or check if product being added is already in cart  each time when user add some product in cart with separate ajax request? 
Is there any beautiful solution for this?

**Comment by kharanenka** [comment]
In our projects, we use [onGetCartData()](http://shopaholic.one/docs#/modules/cart/component/component?id=ongetcartdata) method to get an object with a cart state. Using the cart state object, we determine which method to use: [onAdd()](http://shopaholic.one/docs#/modules/cart/component/component?id=onadd) or [onUpdate()](http://shopaholic.one/docs#/modules/cart/component/component?id=onupdate). 

We use this solution in our npm [package](https://www.npmjs.com/package/@lovata/shopaholic-cart).
