### ISSUE TITLE
why the title of the product page is not the product name?

### ISSUE THREAD

**Issue by forin777** [lovata/oc-shopaholic-plugin#81]
why the title of the product page is not the product name?  <title>{{ this.page.title }}</title>

**Comment by kharanenka** [comment]
Hi! Do you mean demo site?

**Comment by forin777** [comment]
yes .Can  do it? How to?

**Comment by kharanenka** [comment]
Hi! Demo site is an example. It is developed for training developers who start working with Shopaholic`s plugins. SEO function was not developed in this project.
If you need to specify SEO headers for each page, then you need to add a [placeholder](http://octobercms.com/docs/markup/tag-placeholder) in the "main.htm" layout.
