### ISSUE TITLE
Had to manually add Omnipay package

### ISSUE THREAD

**Issue by InquisitiveDevelopment** [lovata/oc-shopaholic-plugin#82]
When trying to create a new "Payment Method" I was getting an error `Class 'Omnipay\Omnipay' not found`. 

I had to do a manual `composer require omnipay/omnipay` to resolve this. Can this be updated so that I no longer need to manually add the package?

**Comment by kharanenka** [comment]
Hi! All right. You need to manually install omnipay packages. This is written in the upgrade guide. We did not specifically add omnipay packages to the plugin  code. Safer way will be if you add packages to the main composer.json file. Otherwise, you can get the package conflict of laravel.
