### ISSUE TITLE
Cart

### ISSUE THREAD

**Issue by robndg** [lovata/oc-shopaholic-plugin#84]
I love the plugin, but the cart is an absolute disaster. The most important aspect of ecommerce.

With Omnipay (what everyone has to use to get money), there are no help documents 
I have it installed no extra fields show when selecting each payment type. With paypal it does not redirect to paypal. Just completed the order.

Shipping Types with added price, does not update total cost on cart page.

The "Checkout" button is lame. It should redirect to more info under the user account for product status, shipping info, cancelling orders and updating.

Any help would be great.

**Comment by kharanenka** [comment]
Hi!
1. Omnipay plugin has only easy integration with omnipay package. It has not ready made methods for payment gateways. Full documentation you can find in documentation of [omnipay](https://github.com/barryvdh/laravel-omnipay) package.
2. > Shipping Types with added price, does not update total cost on cart page.
Do you mean demo site? Demo site is not a ready-made template. It is made for training developers.
3. Methods for render of user order history will be added soon. But do not expect that this will be immediately available in demo theme.
