### ISSUE TITLE
Check quantity on null after update

### ISSUE THREAD

**Issue by vosco88** [lovata/oc-shopaholic-plugin#90]
Hi, 
I am receiving following error when I am making order, it all worked in older version. 

`Call to a member function getObject() on null`
`C:\laragon\www\tmavaochutnavka\plugins\lovata\ordersshopaholic\classes\processor\OfferOrderPositionProcessor.php line 49`

` $this->obOffer = $this->obOfferItem->getObject();`

# | Called Code | Document | Line
-- | -- | -- | --
48 | Lovata\OrdersShopaholic\Classes\Processor\OfferOrderPositionProcessor->check() | ~/plugins/lovata/ordersshopaholic/classes/processor/OrderProcessor.php | 169
47 | Lovata\OrdersShopaholic\Classes\Processor\OrderProcessor->processOrderPositionList() | ~/plugins/lovata/ordersshopaholic/classes/processor/OrderProcessor.php | 62
46 | Lovata\OrdersShopaholic\Classes\Processor\OrderProcessor->create(…) | ~/plugins/lovata/ordersshopaholic/components/MakeOrder.php | 161
45 | Lovata\OrdersShopaholic\Components\MakeOrder->create(…) | ~/plugins/lovata/ordersshopaholic/components/MakeOrder.php | 103

Could you please help? Thank you

**Comment by kharanenka** [comment]
Hi! Fix in version 1.6.2
