### ISSUE TITLE
Question: accesing Order data

### ISSUE THREAD

**Issue by vosco88** [lovata/oc-shopaholic-plugin#91]
Hi,

how can I access the data of offers on the OrderPage component to display them on the page?
I would like to show customer a summary of his order, with name, image, and other info from the Offers.

In previous version I was able to use ProductData component but I cannot get it work after the update.

Thanks for the help.

**Comment by kharanenka** [comment]
Hi! OrderPage component returns [OrderItem](https://github.com/lovata/oc-shopaholic-plugin/wiki/OrderItem) object.
For example:
```
{% set obOrder = OrderPage.get() %}
{% for obOrderPosition in obOrder.order_position %}
  {% set obOffer = obOrderPosition.item %}
  {% set obProduct = obOffer.product %}
  <div>{{ obProduct.name }}</div>
 <div>{{ obOrderPosition.price }}</div>
{% endfor %}
```

**Comment by vosco88** [comment]
Thanks, works like a charm.
