### ISSUE TITLE
Add items to cart

### ISSUE THREAD

**Issue by matthewborgcarr** [lovata/oc-shopaholic-plugin#92]
Can someone please shed some light on how to add items to the cart please??

The documentation says: $.request('Cart::onAdd', { 'data': data, 'update': {'cart-items': '.cart-item-wrapper'} });

how to call this exactly?

Thanks Matthew

**Comment by kharanenka** [comment]
Hi @matthewborgcarr!

You can see example of using Cart component in code of [demo theme](https://github.com/lovata/oc-shopaholic-demo-theme).

You can install local copy of demo site and study code of demo theme.

For example:
https://github.com/lovata/oc-shopaholic-demo-theme/blob/master/themes/shopaholic-demo/assets/js/main.js#L41

**Comment by aarjona1991** [comment]
Hi! i want to know how can i add extra <inputs> to the order. By default the plugin add these:

const cartData = [
      {
        'offer_id': form.find('input[name="offer_id"]').val(),
        'quantity': form.find('input[name="quantity"]').val(),
      }
    ];

In fact i want to add the properties selected. For example 'color', 'size', etc. How can i do that?
Thanks in advance!! :)

**Comment by kharanenka** [comment]
Hi @aarjona1991!
You can find an example [here](https://shopaholic.one/docs#/modules/cart/component/component?id=example-2-add-offers-to-cart-with-properties).

**Comment by aarjona1991** [comment]
@kharanenka Thanks a lot!!! Just what i needed!!
