### ISSUE TITLE
[PropertiesShopaholic] An incorrect value is stored in the database

### ISSUE THREAD

**Issue by milanese** [lovata/oc-shopaholic-plugin#94]
If you type a space (carriage return, <, >) only, then the first value of **Property Values** table will be stored in **Property Value Link** table instead of nothing.

It happens due to an issue with **CommonPropertyHelper**.

**Line №119**
`if (!PropertyValue::hasValue($sValue)) {`

**Line №191**
`$obPropertyValue = PropertyValue::getBySlug($sSlug)->first();`

**PropertyValue::hasValue($sValue)** returns true for spaces (carriage return, <, >). As a result **processPropertyValue()** is called.

**Line №189.**
**$sSlug** is empty for spaces (carriage return, <, >). In this case **getBySlug($sSlug)** doesn't work. 

As a result **PropertyValue::getBySlug($sSlug)** gets all rows from **Property Values** table and **$obPropertyValue** gets the first of them.

Currently I see 2 ways to solve it:
1. Check the value for presence in the table by value not by slug (of course if a slug can be non unique and it's not critical for the plugin architecture)
2. Apply hasValue for the slug in **processValueList()**
```
$sSlug = (!is_array($sValue)) ? PropertyValue::getSlugValue($sValue) : $sValue;

if (!PropertyValue::hasValue($sSlug)) {
    continue;
}
```

The second one solution is more simple and allows to not worry for other code.

**Comment by kharanenka** [comment]
Fixed in version 1.3.2
