### ISSUE TITLE
[Omnipay] Update `payment_data` and `payment_response` after payment success

### ISSUE THREAD

**Issue by philmarc** [lovata/oc-shopaholic-plugin#98]
I am using the new events `'shopaholic.payment_method.omnipay.gateway.cancel_url'` and the 'success_url' which are great.

But when I pay and get redirected to my website (I am using PayPal Express in sandbox mode), the order status doesn't change eventhough I set it up to be "Complete" or "Cancelled" in the backend.

The payment data (Data that was sent and data that was received from payment gateway) are also not filled in. `transaction_id`, `payment_data`, `payment_response`

Where is the logic for updating an order after payment success/cancellation ? 
It would be great to update your Shopaholic demo theme with a working payment gateway (PayPal is the one we all want).

One last thing about the last update is the payment method edit page in the backend:
There are many new fields `firstName`, `billingAddress1`, `shippingCountry`, ... but I am not sure what the purpose of those are, since that data is already present in the lovata buddies additional properties. 
It would be nice to have a field for cancelUrl and returnUrl on that page though.

I really enjoy your plugins, and my website is almost ready to go to production, I just have to make that order update after payment.

Thanks for your help.

**Comment by kharanenka** [comment]
Hi! I now prepare to release plugins for full integration with PayPal and Stripe.
Please wait few more days.

**Comment by philmarc** [comment]
Here are some ideas that could be nice to have in the Shopaholic plugin:

- Add colors to order statuses (ie. green label for 'completed', red for 'cancelled' etc...) (color could be a defined in an input in `backend/lovata/ordersshopaholic/statuses/update/1`)
- Add a tab with a list of trashed orders (`deleted_at` orders) and a list of trashed products (`deleted_at` products) (also add the ability to soft delete an order or a product)
- Downloadable PDF invoice for each order (and also downloadable for the client in his account), with the list of products and the total + shipping (with a customizable template in the backend settings)
- Downloadable EXCEL sheet of the list of orders (filter applyable), and of the active clients in the 'Buddies' plugin tab

Maybe a "Track my order" plugin?
- Ability to fill in a third party tracking number for each order, which will be sent by mail to the client (with a customizable mail template)
- In the frontend, the client can have a form with "email" input and "order_number" input, that once filled would display the tracking number with a link to a third party website (TNT, Chronopost, Royal mail...), plus the date/time that the item was mailed.

**Comment by kharanenka** [comment]
Hi! Good ideas!
We plan to release plugin with  integration of tracking service.
Can you create issues for each idea so that we do not lose them?

P.S. PayPal for Shopaholic plugin will be sent for moderation tomorrow. I just wait for icon from designer.
